[colors.primary]
background = "#0a0f1c"
foreground = "#d4d5d9"

[colors.cursor]
text = "#0a0f1c"
cursor = "#d4d5d9"

[colors.vi_mode_cursor]
text = "#0a0f1c"
cursor = "#d4d5d9"

[colors.search.matches]
foreground = "#0a0f1c"
background = "#d4d5d9"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f6374"
background = "#d4d5d9"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0f1c"
red = "#869AAC"
green = "#95A8B8"
yellow = "#9FADB8"
blue = "#9BB0C2"
magenta = "#A8B9C6"
cyan = "#B8C7D0"
white = "#d4d5d9"

[colors.bright]
black = "#5f6374"
red = "#869AAC"
green = "#95A8B8"
yellow = "#9FADB8"
blue = "#9BB0C2"
magenta = "#A8B9C6"
cyan = "#B8C7D0"
white = "#d4d5d9"

[colors.dim]
black = "#d4d5d9"
red = "#869AAC"
green = "#A8B9C6"
yellow = "#9FADB8"
blue = "#9BB0C2"
magenta = "#95A8B8"
cyan = "#B8C7D0"
white = "#5f6374"
